FROM docker.io/library/debian:bookworm-slim

ARG DEBIAN_FRONTEND=noninteractive

COPY . /static

RUN \
	apt update; \
	apt install --no-install-recommends -y \
	git sqlite3 build-essential libtool autotools-dev automake pkg-config \
	bsdmainutils python3 libevent-dev libboost-dev libsqlite3-dev tor wget \
	ca-certificates; \
	/static/scripts/bitcoind/build.sh

ENTRYPOINT ["/static/scripts/bitcoind/init.sh"]
