services:
  bitcoind:
    container_name: bitcoind
    build: ./containers/bitcoind
    working_dir: /app
    volumes:
      - ./containers/bitcoind/volume:/app
    ports:
      - 8332:8332
      - 18443:18443
      - 18332:18332
    networks:
      - bitcoind 

networks:
  bitcoind:
    name: bitcoind
    external: true
